Default outbound to true if href is external
metonym/svelte-link pull request #3
Opened 2020-11-28 23:33 UTC by seaneking

Closes #2

2020-11-28 23:35 UTC, seaneking commented on src/Link.svelte
> +    target = '_blank';
Sorry seems my prettier config overrode these double quotes, happy to revert

2020-11-29 23:48 UTC, metonym requested changes

2020-11-29 23:48 UTC, metonym commented on src/Link.svelte
> +  $: if (process.browser) {
What's the reason for this? Can it be taken out?

EDIT: I'm guessing it's a guard for Sapper?

In my case, I'm unable to run it with a non-SSR Rollup set-up. I wonder if `window.URL` is a better substitute

2020-11-30 00:45 UTC, seaneking commented on src/Link.svelte
> +  $: if (process.browser) {
Whoops, you're totally correct it's a Sapper thing. Sorry I got muddied up between Svelte and Sapper APIs. `window && window.URL` would be a much better substitute, I'll update it

2020-11-30 00:48 UTC, seaneking commented
Updated window check and added a note about new `outbound` behaviour to README

2020-11-30 00:55 UTC, metonym approved these changes
Nice!

2020-11-30 00:55 UTC, merged